spring:
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    platform: postgres
    url: postgres://euahhembidkqzh:882f7db5376b777ad78061d13050b1e224dea62a3bb160b73f287899e5695405@ec2-54-75-246-118.eu-west-1.compute.amazonaws.com:5432/d2ud0c78k0s33t
    username: euahhembidkqzh
    password: 882f7db5376b777ad78061d13050b1e224dea62a3bb160b73f287899e5695405
    driverClassName: org.postgresql.Driver